language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 7
  - nightly
  - hhvm
  
matrix:
  allow_failures:
    - php: hhvm
    - php: 7
    - php: nightly

before_script: 
  - composer self-update
  - composer install --dev --no-interaction --prefer-dist
script:
  - mkdir -p build/logs
  - phpunit --testdox --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
