dist: trusty

language: php

sudo: false

php:
  - 5.6
  - 5.5
  - 5.4
  - 7

cache:
  directories:
    - $HOME/.composer/cache

before_script: 
  - composer self-update
  - composer install --dev --no-interaction --prefer-dist

script:
  - mkdir -p build/logs
  - phpunit
