language: php
php:
  - 5.5
  - 5.4

before_script: composer install --dev --no-interaction --prefer-dist
script:
  - mkdir -p build/logs
  - phpunit --testdox --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v