dist: trusty

language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache

before_script: 
  - composer self-update
  - composer install --no-interaction --prefer-dist

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit
